@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Mar 13 21:37:36 -0700 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim dp_tb_top_behav -key {Behavioral:sim_1:Functional:dp_tb_top} -tclbatch dp_tb_top.tcl -view C:/Users/Steven/Desktop/Verilog/Lab4/data_path/dp_tb_top_behav.wcfg -log simulate.log"
call xsim  dp_tb_top_behav -key {Behavioral:sim_1:Functional:dp_tb_top} -tclbatch dp_tb_top.tcl -view C:/Users/Steven/Desktop/Verilog/Lab4/data_path/dp_tb_top_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
