import graphviz as gv
dot = gv.Digraph()
dot.node('bb0', shape='record', label="<b>BB0 | {3:const #0}" )
dot.node('bb1', shape='record', label="<b>BB1 | {1: read|2: add (1) (1)|4: cmp (1) (3)|5: bge (4) (10)}" )
dot.node('bb2', shape='record', label="<b>BB2 | {6: add (2) (2)|9: bra (7)}" )
dot.node('bb3', shape='record', label="<b>BB3 | {10: \<empty\>}" )
dot.node('bb4', shape='record', label="<b>BB4 | {7: phi (6) (2)|8: phi (6) (1)|11: write (8)}" )

dot.edge('bb0:s', 'bb1:n')
dot.edge('bb1:s', 'bb2:n', label="fall-through")
dot.edge('bb1:s', 'bb3:n', label="branch")
dot.edge('bb2:s', 'bb4:n', label="branch")
dot.edge('bb3:s', 'bb4:n', label="fall-through")
dot.edge('bb1:b', 'bb2:b', color='blue', style='dotted', label="dom")
dot.edge('bb1:b', 'bb3:b', color='blue', style='dotted', label="dom")
dot.edge('bb1:b', 'bb4:b', color='blue', style='dotted', label="dom")
print(dot.source)